
management:
  server:
    port: 8889

  endpoints:
    web:
      base-path:
      exposure:
        include: '*'

eureka:
  client:
    enabled: true
spring:
  cloud:
    config:
      override-none:


